import { readdir, readFile, writeFile } from "node:fs/promises";
import { build } from "tsdown";
import ts from "typescript-api";

const packageJson = JSON.parse(
  await readFile(new URL("../package.json", import.meta.url), "utf8"),
);
await writeFile(
  new URL("../src/version.ts", import.meta.url),
  `// Generated by scripts/build.mjs from package.json.\nexport const PACKAGE_NAME: string = ${JSON.stringify(packageJson.name)};\nexport const PACKAGE_VERSION: string = ${JSON.stringify(packageJson.version)};\n`,
);

if (!process.argv.includes("--metadata-only")) {
  const dist = new URL("../dist/", import.meta.url);
  await build({ config: "tsdown.config.ts" });

  for (const file of await readdir(dist)) {
    if (!file.endsWith(".js") && !file.endsWith(".d.ts")) continue;
    const location = new URL(file, dist);
    let text = await readFile(location, "utf8");
    const source = ts.createSourceFile(
      file,
      text,
      ts.ScriptTarget.Latest,
      true,
    );
    const edits = [];
    for (const statement of source.statements) {
      if (
        !ts.isImportDeclaration(statement) &&
        !ts.isExportDeclaration(statement)
      )
        continue;
      const specifier = statement.moduleSpecifier;
      if (!specifier || !ts.isStringLiteral(specifier)) continue;
      if (
        !specifier.text.startsWith("@modelcontextprotocol/sdk/") ||
        !specifier.text.endsWith(".js")
      )
        continue;
      const typesSpecifier = specifier.text.slice(0, -3);
      // SDK 1.30's wildcard type export appends .d.ts to an existing .js suffix.
      // Node must keep .js runtime imports; JSR needs the extensionless type path.
      if (file.endsWith(".d.ts")) {
        edits.push({
          start: specifier.getStart(source),
          end: specifier.end,
          text: JSON.stringify(typesSpecifier),
        });
      } else {
        edits.push({
          start: statement.getStart(source),
          end: statement.getStart(source),
          text: `/* @ts-types=${JSON.stringify(typesSpecifier)} */\n`,
        });
      }
    }
    for (const edit of edits.sort((a, b) => b.start - a.start)) {
      text = text.slice(0, edit.start) + edit.text + text.slice(edit.end);
    }
    if (file.endsWith(".js")) {
      const directive = `/* @ts-self-types="./${file.slice(0, -3)}.d.ts" */\n`;
      const offset = text.startsWith("#!") ? text.indexOf("\n") + 1 : 0;
      text = text.slice(0, offset) + directive + text.slice(offset);
    }
    await writeFile(location, text);
  }
}
